### ISSUE TITLE
代码块在 iphone 手机无法滚动

### ISSUE THREAD

**Issue by shenweiyan** [zhning12/markdown-nice#12]
发现在最新版本 Chrome 编辑好的文章，粘贴到公众号后，代码块在 iphone 手机无法左右滚动，在安卓手机中滚动却是正常的。

[Md2All](http://md.aclickall.com/) 也有这个问题（作者不知道为什么一直都没有修复），但是在 Firefox 中是没问题的。

最好，谢谢作者的这个工具，希望越来越好！

**Comment by guanpengchn** [comment]
代码块指的是哪种代码样式，微信代码样式是有行号可以左右滚动的，用起来也好用，比如这篇文章

https://mp.weixin.qq.com/s/_NdAjbWlYDV7z7LvMpuyDA

**Comment by StephanXu** [comment]
目前来讲只有微信自带的代码样式是正常的，但是有时候需要高亮效果的话，微信自带的代码样式就无法提供支持了

**Comment by guanpengchn** [comment]
@StephanXu 其他的代码样式有什么问题么？还有的话微信自带的代码样式是不是哪种语言无法提供支持？

**Comment by StephanXu** [comment]
@guanpengchn 除了微信自带的，貌似其他的都是这样，如果一行过长会直接挤到下一行去，不会有微信默认样式的那种横向滚动条

**Comment by guanpengchn** [comment]
@StephanXu 嗯嗯，目前来说确实如此，之前没有特意去调试这个功能，之后去测一下其他样式是否可以不换行

**Comment by StephanXu** [comment]
好的，期待您的新版本，感谢。希望越来越好

**Comment by shenweiyan** [comment]
> @guanpengchn 除了微信自带的，貌似其他的都是这样，如果一行过长会直接挤到下一行去，不会有微信默认样式的那种横向滚动条

的确如 StephanXu 所说的那样，不知道是不是浏览器的问题。

**Comment by guanpengchn** [comment]
@shenweiyan 微信这个编辑器确实让人捉摸不透，其实滚动条是加了的，但是预览之后没有

**Comment by guanpengchn** [comment]
已经可以不换行滚动了，现在默认为不换行

```
/* 非微信代码块
 * 代码块不换行 display: -webkit-box !important;
 * 代码块换行 display: block;
 */
pre code {
}
```
