### ISSUE TITLE
可以调整代码块中字体大小么

### ISSUE THREAD

**Issue by maxadd** [zhning12/markdown-nice#13]
我没有找到相关的，是没有还是我没有找到？

感谢作者提供了这么好用的工具。

**Comment by guanpengchn** [comment]
@maxadd 没有的，这个原因是这样的，微信代码主题无论怎么调节最后都会和微信公众号的编辑器统一。其他代码主题主要考虑到要调节的css太多，所以就选择了有限的主题和固定测试好的样式，而且也觉得调整代码块的需求应该不大。您这边的具体情况是什么样的？

**Comment by maxadd** [comment]
哦，主要是我调大了下整体的字体，这样就显得代码块中的字体过小，有些突兀，其他的没啥。

**Comment by guanpengchn** [comment]
```css
pre code {
  font-size: 18px;
}
```
可以用这个属性，我之后把这个属性放出来

**Comment by maxadd** [comment]
厉害了大佬，多谢！

**Comment by guanpengchn** [comment]
已经添加了该属性
