### ISSUE TITLE
h2 标题与普通加粗的字体一样大

### ISSUE THREAD

**Issue by biaochenxuying** [zhning12/markdown-nice#14]
楼主你好，h2 标题与普通加粗的字体一样大了，正常来说： h2 的标题比 普通的加粗大很多的。

![image](https://user-images.githubusercontent.com/24362914/60408755-d043b580-9bf2-11e9-89ac-6e44184be709.png)

**Comment by zhning12** [comment]
感谢您的建议~

这个主题是其他用户贡献的自己的css样式~所以出现了h2和粗体的字体大小相同的情况，在其他主题下是没有这个情况的~

如果您喜爱这个主题，但是对于某些字体大小、颜色的细节有自己的需求，可以点开右上角自定义样式进行定制化的修改（会实时生效）。如果对自己修改的样式较为满意，修改后可以将该样式文件先保存在本地，以后转换时替换即可。
（后续会考虑以恰当的方式增加保存自定义样式的功能，目前暂时只能通过手动替换修改来实现）

同时如果您有好的主题，也欢迎分享，非常感谢您的关注和issue~
![image](https://user-images.githubusercontent.com/28998173/60409157-ed798380-9bf4-11e9-8d78-a2ca2d260ed0.png)

**Comment by biaochenxuying** [comment]
明白了，谢谢楼主。

**Comment by guanpengchn** [comment]
@biaochenxuying 目前已经改成22px了，看着会正常一些
