### ISSUE TITLE
非 mp.weixin.qq.com 的url链接无法插入

### ISSUE THREAD

**Issue by purequant** [zhning12/markdown-nice#15]
您这个工具一键转化后，排版很漂亮。但是非mp.weixin.qq.com 的url链接，在微信公众号中其实是无法插入的，还需要手动去删除太麻烦了。能不能将连接像[这个转换工具](https://lab.lyric.im/wxformat/)一样做成**References**

**Comment by guanpengchn** [comment]
您这个意见很中肯，这个我们之前考虑过，是否要将外链直接转成references，后来没有这样做的原因是该排版工具并不是只针对微信公众号使用，其他平台使用的时候外链是可以添加的，如果统一转成references的话，对于其他平台来说不是好做法。

所以探讨之后，认为目前比较合理的使用方案是，在链接里面添加双引号，加上脚注名字就可以自动转换成脚注，如果不加则是链接

```md
脚注：[文字](脚注解释 "脚注名字")
```

如下图所示：

<img width="337" alt="1" src="https://user-images.githubusercontent.com/13995641/61572132-c57e9100-aacb-11e9-8124-b101819a1c25.png">

**这个确实是个问题，解决该问题我们会考虑区分微信平台和其他平台**

**Comment by luwantaoChina** [comment]
好的，明白了，非常感谢

**Comment by guanpengchn** [comment]
更新v1.0.1版本，新增粘贴时语法检测功能，可转换微信外链
