### ISSUE TITLE
代码中含有数学公式，转换似乎难以完成？

### ISSUE THREAD

**Issue by purequant** [zhning12/markdown-nice#19]
你好，如果markdown文件中含有数学latex数学公式，那么转换的时候非常慢，而且似乎难以完成。
![image](https://user-images.githubusercontent.com/26440503/62834745-453eec00-bc83-11e9-93e4-d6ad755309c9.png)

**Comment by guanpengchn** [comment]
我看了下，这里有bug，如果你再点击下复制，是能复制上的

**Comment by purequant** [comment]
我这里点击第二下复制的时候，复制过去的是markdown原文件

**Comment by YouhuaLi** [comment]
顶一下楼主，同样的情况。好像是无法上传图片。

**Comment by guanpengchn** [comment]
这里我看了下，是默认图床的问题，它会检测是否有相同的图片上传，这里我没做错误处理，这个问题需要支持自定义图床后再解决

**Comment by purequant** [comment]
这个不是图片的问题吧，我的公式都是latex代码啊，这里应该不存在转换一说才对啊。而且其他图片都是能正常copy到微信的

**Comment by guanpengchn** [comment]
@purequant 微信不支持公式，放进去就会错乱，所以要转成图片使用图床上传，获取链接然后再复制，最后粘贴过去

**Comment by guanpengchn** [comment]
@purequant 提供我一份markdown，我晚上测试下

**Comment by purequant** [comment]
好的，这是文件。

[upload_test.zip](https://github.com/zhning12/markdown-nice/files/3497003/upload_test.zip)

**Comment by guanpengchn** [comment]
@purequant 图床发布测试版之后解决公式问题

**Comment by guanpengchn** [comment]
@purequant 你的文件能跑通了，之前有一个bug，已经修复，我用自己的阿里云图床转换速度比较快，测试可以通过，不过目前依然存在行内公式过大，块公式不全的问题

**Comment by guanpengchn** [comment]
@purequant @YouhuaLi 公式问题已经解决，这是我目前找到的最好解决方案，可以体验一下
