### ISSUE TITLE
WeChat format 样式含有TOC目录的markdown转换存在问题？

### ISSUE THREAD

**Issue by purequant** [zhning12/markdown-nice#20]
形如这样的TOC:

![image](https://user-images.githubusercontent.com/26440503/62834828-3278e700-bc84-11e9-855f-5dfbb60da63d.png)

转换后还是存在链接：

![image](https://user-images.githubusercontent.com/26440503/62834853-67853980-bc84-11e9-8899-9cf2f7312179.png)

而这种链接wechat中仍不支持

**Comment by guanpengchn** [comment]
更新v1.0.1版本，新增粘贴时语法检测功能，可转换微信外链

**Comment by guanpengchn** [comment]
Duplicate of #15
