### ISSUE TITLE
Firefox下点击“复制”按钮报错

### ISSUE THREAD

**Issue by missdeer** [zhning12/markdown-nice#24]
Chrome没问题

**Comment by guanpengchn** [comment]
@missdeer 推荐用chrome，晚上我看下是否能兼容firefox

**Comment by zhning12** [comment]
您好，不知道是否能提供更加详细的情况（比如md文本和报错内容），我测试了默认的文本，是没有问题的，不知道您遇到的是什么bug呢？

**Comment by zhning12** [comment]
> Chrome没问题

您好，不知道是否能提供更加详细的情况（比如md文本和报错内容），我测试了默认的文本，是没有问题的，不知道您遇到的是什么bug呢？

**Comment by missdeer** [comment]
Firefox 68.0.2
Windows 10/macOS 10.14.6
打开 https://mdnice.com，默认文本，点击页面顶部蓝色“复制”按钮，报“window.returnCitySN is undefined”

**Comment by missdeer** [comment]
抱歉，我的错，Firefox把一些js屏蔽了。

**Comment by guanpengchn** [comment]
@missdeer 想问下是安装了插件么，导致了屏蔽该js，我想了解下，如果该js被屏蔽的概率很高，我就去掉

**Comment by missdeer** [comment]
@guanpengchn uBlock Origin
