### ISSUE TITLE
fork 之后，怎么修改成自己的多套样式来使用？

### ISSUE THREAD

**Issue by cmmei** [zhning12/markdown-nice#25]
如题，fork 之后，想要修改成自己的多套样式，然后给同事使用。需要修改哪些配置？

**Comment by guanpengchn** [comment]
@cmmei 主题相关代码在[此处](https://github.com/zhning12/markdown-nice/tree/master/src/template)，选项卡在[constant.js](https://github.com/zhning12/markdown-nice/blob/master/src/utils/constant.js)中

**Comment by cmmei** [comment]
谢谢。我试试。
