### ISSUE TITLE
上传图片，用 sm.ms 显示网络错误

### ISSUE THREAD

**Issue by cmmei** [zhning12/markdown-nice#26]
上传图片，用 sm.sm 显示万靓错误，但我直接在 sm.ms 网站上传是可以的。

**Comment by guanpengchn** [comment]
@cmmei 图片超过十张会有问题，这个暂时没处理，我刚刚试了没报错，发个截图看下

**Comment by cmmei** [comment]
就一张图片额。
![image](https://user-images.githubusercontent.com/11864255/63752277-90900600-c8e3-11e9-982b-e066b5fb1fa3.png)

**Comment by guanpengchn** [comment]
![1](https://user-images.githubusercontent.com/13995641/63753040-e3b68880-c8e4-11e9-932b-06ee4ee4779f.jpg)

![2222](https://user-images.githubusercontent.com/13995641/63753098-05b00b00-c8e5-11e9-8551-0d26120f7382.jpg)

发来看看

**Comment by guanpengchn** [comment]
@cmmei 还有错误消息么，没有的话就关掉了

**Comment by cmmei** [comment]
嗯，我重新安装后没错误消息了。谢谢。

在 2019年8月31日週六 10:02，灵魂画师牧码 <notifications@github.com> 寫道：

**Comment by guanpengchn** [comment]
嗯嗯好的好的
