### ISSUE TITLE
一直报错 “行内公式格式错误，无法进行转换”

### ISSUE THREAD

**Issue by OHeroJ** [zhning12/markdown-nice#27]

**Comment by guanpengchn** [comment]
是不是有两个$符号在一行

**Comment by OHeroJ** [comment]
Access to XMLHttpRequest at 'https://math.mdnice.com/182.100.0.41/%E6%B1%9F%E8%A5%BF%E7%9C%81' from origin 'https://www.mdnice.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by OHeroJ** [comment]
> 是不是有两个$符号在一行

没有用 $ 符号

**Comment by OHeroJ** [comment]
> Access to XMLHttpRequest at 'https://math.mdnice.com/182.100.0.41/%E6%B1%9F%E8%A5%BF%E7%9C%81' from origin 'https://www.mdnice.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

这个在报错

**Comment by guanpengchn** [comment]
@OHeroJ 方便把出错部分的markdown发我么？邮箱也可以，875499765@qq.com

**Comment by OHeroJ** [comment]
> 875499765@qq.com

已发

**Comment by guanpengchn** [comment]
@OHeroJ 已解决，这里存在代码块内公式误识别问题

**Comment by OHeroJ** [comment]
> @OHeroJ 方便把出错部分的markdown发我么？邮箱也可以，[875499765@qq.com](mailto:875499765@qq.com)

有啥问题么？

**Comment by guanpengchn** [comment]
是这样的，加入公式识别之后，会使用正则表达式`/\$(.*?)\$/g`进行匹配，导致代码段中的也被匹配到了，也就是你的这一行，一行内存在两个$符号，被认为存在行内公式，但是实际上是没有的，这里之后需要处理代码段公式的识别问题

```
let possibleSquare = possibleNumber.map { $0 * $0 }
```

**Comment by OHeroJ** [comment]
> @OHeroJ 已解决，这里存在代码块内公式误识别问题

3Q, markdown 的样式不错! 🐂

**Comment by guanpengchn** [comment]
不客气，感谢使用和反馈，帮我们发现了bug，哈哈
