### ISSUE TITLE
复制时出现“window.returnCitySN is undefined”错误信息提示

### ISSUE THREAD

**Issue by leelongcrazy** [zhning12/markdown-nice#28]
**运行环境： **

|操作系统|浏览器|
|---|---|
|macOS|Chrome|

**Markdown文本内容：**

例如：部分文本内容
| 比较项 | 可控硅 | PWM | 0-10V |
| --- | --- |  --- | --- |
| 原理 | 物理性质的调光，调节交流电每个半波的导通角来改变正弦波形，从而改变交流电流的有效值，以此实现调光的目的 | 对模拟信号电平进行数字编码的方法 | 一种模拟调光方式，通过改变0-10V的电压来控制电源的输出电流从而达到调光 |
**错误详情：**
复制时弹窗提示错误信息
window.returnCitySN is undefined

**Comment by guanpengchn** [comment]
@leelongcrazy 我刚刚在部署代码，现在还有上述现象么

**Comment by guanpengchn** [comment]
@leelongcrazy 我大概知道了，应该是使用了广告拦截器一类的插件导致的，我在代码里加入了一个外界的js用于通过ip区分用户的，我之后考虑去掉该脚本

**Comment by guanpengchn** [comment]
@leelongcrazy 已经去除相关脚本，不会再有该报错了
