### ISSUE TITLE
块级公式格式错误，无法进行转换

### ISSUE THREAD

**Issue by lxfriday** [zhning12/markdown-nice#29]
**运行环境：**

|操作系统|浏览器|
|---|---|
|windows|Chrome|

Google Chrome Version 76.0.3809.132 (Official Build) (64-bit)

**出错md：**
---
`Provider` `Consumer` 是 context 的两个属性。
```js
  var context = {
    $$typeof: REACT_CONTEXT_TYPE,
    _currentValue: defaultValue,
    _currentValue2: defaultValue,
    Provider: null,
    Consumer: null
  };
```

`Provider` 的 `$$typeof` 是 `REACT_PROVIDER_TYPE`，它带有一个 `_context` 属性，指向的就是 `context` 本身，也就是自己的儿子有一个属性指向自己！！！

```js
  context.Provider = {
    $$typeof: REACT_PROVIDER_TYPE,
    _context: context
  };
```
`Consumer` 的 `$$typeof` 是 `REACT_CONTEXT_TYPE`，它带也有一个 `_context` 属性，也是自己的儿子有一个属性指向自己！！！

```js
  var Consumer = {
    $$typeof: REACT_CONTEXT_TYPE,
    _context: context,
    _calculateChangedBits: context._calculateChangedBits
  };

```

所以可以做一个猜想， `Provider` 的 value 属性赋予的新值肯定通过 `_context` 属性传到了 `context` 上，修改了 `_currentValue`。同样，`Consumer` 也是依据 `_context` 拿到了 `context` 的 `_currentValue`，然后 `render(newValue)` 执行 `children` 函数。

---
**错误详情：**

块级公式转换错误，控制台不报错

**Comment by lxfriday** [comment]
我把所有的 $$ 删除之后恢复正常，但这不是我想要的

**Comment by guanpengchn** [comment]
收到，我晚上处理下

**Comment by guanpengchn** [comment]
@lxfriday 已经解决

**Comment by lxfriday** [comment]
好的，多谢了
