### ISSUE TITLE
图片粘贴即上传

### ISSUE THREAD

**Issue by lxfriday** [zhning12/markdown-nice#30]
**新特性描述：**
类似掘金，截图之后，在编辑器中粘贴图片就可以自动上传图片，这个功能很实用，因为现在主要在掘金写文章，图片上传到他们那有盗链处理，没办法全平台使用。

**Comment by lxfriday** [comment]
我可以帮忙来做这个

**Comment by guanpengchn** [comment]
@lxfriday 这个功能的话，目前mdnice也没有图床能够完全保证上传的图片可用，每个图床都有自己的问题，可以重置后见介绍，不过粘贴图片自动上传确实可以做，欢迎

**Comment by lxfriday** [comment]
@guanpengchn  好的，我尝试着做做
