### ISSUE TITLE
七牛图片上传之后，域名应该修改为我自己的域名

### ISSUE THREAD

**Issue by lxfriday** [zhning12/markdown-nice#31]
**运行环境：**

|操作系统|浏览器|
|---|---|
|windows|Chrome|

**Markdown文本内容：**

七牛图片上传成功了，但是域名是 mdnice 的，需要有一个配置自己的域名的地方，以免每次上传完都要更改为自己的域名

**Comment by lxfriday** [comment]
自动生成的文件地址，访问不了

![image](https://user-images.githubusercontent.com/20264467/64467919-9c37c400-d150-11e9-8d17-7b27ab365c5c.png)

**Comment by lxfriday** [comment]
我在帮忙改这个问题，另外我打算在 dialog 里面加入**自定义文件名**，这样方便做文件分类

**Comment by guanpengchn** [comment]
@lxfriday 是这样的，mdnice图床是使用的我个人的图床，里面都是我个人的配置信息，所以为了安全，这里是在后台去上传图片的，后台的源代码是不公开的，所以域名无法修改，因为是我个人的，文件名的话我也考虑过，只不过这个粒度不太好控制，做多了很可能会需要做一整台图片管理工具，有的话我觉得很好，不过这里可能工作量很大

**Comment by guanpengchn** [comment]
@lxfriday 方便的话可以加我微信沟通，aaron875499765

**Comment by lxfriday** [comment]
@guanpengchn 申请了，麻烦通过下
