### ISSUE TITLE
使用smms图床，粘贴到微信编辑器提示图片上传失败

### ISSUE THREAD

**Issue by Smilefisher945** [zhning12/markdown-nice#34]
使用smms图床，使用连接直接访问图片正常，粘贴到微信编辑器提示图片上传失败。

**Comment by guanpengchn** [comment]
@Smilefisher945 请重置后看一下第十条的介绍，有写这种情况

**Comment by Smilefisher945** [comment]
好的，感谢。






------------------ 原始邮件 ------------------
发件人: "灵魂画师牧码"<notifications@github.com>; 
发送时间: 2019年9月10日(星期二) 晚上11:05
收件人: "zhning12/markdown-nice"<markdown-nice@noreply.github.com>; 
抄送: "506960904"<yuhong7243@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [zhning12/markdown-nice] 使用smms图床，粘贴到微信编辑器提示图片上传失败 (#34)




@Smilefisher945 请重置后看一下第十条的介绍，有写这种情况
