### ISSUE TITLE
使用mdnice自带图床，复制到微信显示图片上传失败

### ISSUE THREAD

**Issue by Roy-Kid** [zhning12/markdown-nice#40]
![image](https://user-images.githubusercontent.com/42854324/65428719-71838600-de47-11e9-8c9c-70585eeb9e72.png)
编辑的时候上传很正常，复制到微信就8行。更诡异的是有一部分成功有一部分失败。更更诡异的是有些时候失败的也能看到图，但是就是提示上传不成功，只有你把图删了手动上传才行，替换都不行。

**Comment by guanpengchn** [comment]
@Roy-Kid 图片大小有没有超过5M

**Comment by guanpengchn** [comment]
@Roy-Kid 方便的话把图片打包上传我调试一下

**Comment by Roy-Kid** [comment]
竟然还有邮件通知。我明天把照片发给您，平均大小一百多kb。

**Comment by guanpengchn** [comment]
@Roy-Kid 没问题，也欢迎加入微信用户群，方便交流

**Comment by guanpengchn** [comment]
我测试了下我这里上传了22张图片，粘贴失败之后，全删掉再次粘贴，3次之后没有失败的了，你可以试试多粘贴几次，这个没法完全避免，还有就是要确保自身网络稳定

**Comment by Roy-Kid** [comment]
不好意思今天在实验室忙一天忘了这茬了。我一开始以为是图床有问题，微信公众平台读不出来。今天八张图倒是一次成功了。我在观察一段时间吧，之前几次失败大多是因为图很多，二三十张，而且图裂了他在微信那个编辑器里没有显示，没办法就得把所有图都删了重新添加。issue可以先close了，我加微信群有问题随时沟通。麻烦您了，谢谢，工具非常好用！
