### ISSUE TITLE
复制到微信时多出空行

### ISSUE THREAD

**Issue by tansongchen** [zhning12/markdown-nice#41]
**运行环境：**

|操作系统|浏览器|
|---|---|
|macOS|Chrome|

**HTML 内容：**

例如：

```html
<section id="frontmatter">
    <section id="frontmatter-left">
        <img id="avatar" src="https://tva1.sinaimg.cn/large/006y8mN6gy1g73qxb4k8xj30dw0dwgmu.jpg">
        <p id="name">谭淞宸</p>
    </section>
    <section id="frontmatter-right">
        <p id="number">Vol. 00</p>
        <p id="word-count">📝 0.0 千字</p>
        <p id="time-estimation">🕒 0.0 分钟</p>
    </section>
</section>
```

对应的 CSS 见附件[黄.txt](https://github.com/zhning12/markdown-nice/files/3644582/default.txt)。

**错误详情：**

在 Nice 编辑器内部显示正确：

![](https://tva1.sinaimg.cn/large/006y8mN6ly1g7a9tqntwnj30j60d2q3e.jpg)

但复制到微信时凭空多出了一个空行：

![](https://tva1.sinaimg.cn/large/006y8mN6ly1g7a9uqnkr2j30vq0eidgc.jpg)

通过检查发现空行中有几个空格：

![](https://tva1.sinaimg.cn/large/006y8mN6ly1g7a9wdby3zj323k0oqgoi.jpg)

请问这有可能是什么原因？

**Comment by guanpengchn** [comment]
```xml
[空格][空格][空格][空格]<p id="name">谭淞宸</p>
```
该标签前面使用了四个空格导致该问题出现，建议删掉空格，或者使用tab，即可避免上述问题
