### ISSUE TITLE
请检查行内公式是否包含空格或中文

### ISSUE THREAD

**Issue by krahets** [zhning12/markdown-nice#42]
- $a=1$

类似如上的写法会报错：

>提示：请检查行内公式是否包含空格或中文。
>$a=1$

当改成这种写法时就不会报错了：
- $a \equiv 1$

测试`+*-`这类运算符也会报错，请问是无法直接使用这些符号吗？

**Comment by guanpengchn** [comment]
@krahets 我这里没有复现该错误，我用上述写法是正常的，有没有截图

**Comment by krahets** [comment]
![image](https://user-images.githubusercontent.com/26993056/65487050-9e33ae00-ded8-11e9-922f-e161aebef019.png)
![image](https://user-images.githubusercontent.com/26993056/65487061-a2f86200-ded8-11e9-875f-d11fec424680.png)

**Comment by krahets** [comment]
![image](https://user-images.githubusercontent.com/26993056/65487204-f2d72900-ded8-11e9-9767-65c8aaa29609.png)

**Comment by guanpengchn** [comment]
你误解这个提示了，这个提示表示$a/1$这个公式被成功检测到了，是没有问题的，有问题的是其他的没有被检测到的公式，比如下面这两个，里面就包含空格，导致这两个公式无法被检测到

![公式错误](https://user-images.githubusercontent.com/13995641/65487317-35990100-ded9-11e9-83c4-abff9c0aa506.jpg)

**Comment by guanpengchn** [comment]
这个提示内容之后改进

**Comment by krahets** [comment]
噢噢~但是我删除$a=1$后，并没有报错啊，上面有空格的那两行也被正确识别了，这篇推文也是显示正常的。

![image](https://user-images.githubusercontent.com/26993056/65487587-bf48ce80-ded9-11e9-8d2f-6a54d0ee599d.png)

![image](https://user-images.githubusercontent.com/26993056/65487592-c4a61900-ded9-11e9-810a-3b5a12d5b6a7.png)

这是我在公众号已经推出去的文章。

![image](https://user-images.githubusercontent.com/26993056/65487625-dd163380-ded9-11e9-8757-83a1aff019d4.png)

**Comment by guanpengchn** [comment]
@krahets 全文发我下吧，875499765@qq.com

**Comment by guanpengchn** [comment]
@krahets 欢迎加入用户群，交流方便

**Comment by krahets** [comment]
好的

**Comment by guanpengchn** [comment]
已经更新提示信息
