### ISSUE TITLE
需要自定义图床的feature

### ISSUE THREAD

**Issue by YouhuaLi** [zhning12/markdown-nice#7]
工具很忙，但是能自定义图床很重要。我的公众号需要有很多数学公式，就是因为微信屏蔽了七牛云的免费域名才放弃md2all的。sm.ms的图片似乎也是屏蔽的。

我希望能有自定义图传功能，希望有限实现aliyun的，谢谢：）

**Comment by guanpengchn** [comment]
嗯嗯，图床确实是个比较大的问题，SM.MS不够稳定，甚至阿里云也存在过粘贴图片失败的现象，后面会加入自定义图床

**Comment by guanpengchn** [comment]
@YouhuaLi 阿里云OSS已经实现，在做测试，之后会发布文档如何使用

**Comment by guanpengchn** [comment]
@YouhuaLi 自定义图床功能已经测试完毕，欢迎使用

**Comment by YouhuaLi** [comment]
太棒了！
